// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SmartKitchenAssistant.Api.Infrastructure.Persistence;

#nullable disable

namespace SmartKitchenAssistant.Api.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(SmartKitchenDbContext))]
    [Migration("20260928132747_UseExactBinaryPantryUserId")]
    partial class UseExactBinaryPantryUserId
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SmartKitchenAssistant.Api.Features.Catalog.Domain.Ingredient", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("QuantityDimension")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.HasKey("Id");

                    b.ToTable("Ingredients", "catalog", t =>
                        {
                            t.HasCheckConstraint("CK_Ingredients_QuantityDimension", "[QuantityDimension] IN (N'Mass', N'Volume', N'Count')");
                        });
                });

            modelBuilder.Entity("SmartKitchenAssistant.Api.Features.Pantry.Domain.UserPantryItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("DisplayUnit")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<long>("IngredientId")
                        .HasColumnType("bigint");

                    b.Property<decimal>("NormalizedQuantity")
                        .HasPrecision(18, 6)
                        .HasColumnType("decimal(18,6)");

                    b.Property<byte[]>("UserId")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("varbinary(512)");

                    b.HasKey("Id");

                    b.HasIndex("IngredientId");

                    b.HasIndex("UserId", "IngredientId")
                        .IsUnique();

                    b.ToTable("UserPantryItems", "pantry", t =>
                        {
                            t.HasCheckConstraint("CK_UserPantryItems_DisplayUnit", "[DisplayUnit] IN (N'Gram', N'Kilogram', N'Milliliter', N'Liter', N'Each')");

                            t.HasCheckConstraint("CK_UserPantryItems_NormalizedQuantity_Positive", "[NormalizedQuantity] > 0");
                        });
                });

            modelBuilder.Entity("SmartKitchenAssistant.Api.Features.Recipes.Domain.Recipe", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("BaseServings")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Recipes", "recipes", t =>
                        {
                            t.HasCheckConstraint("CK_Recipes_BaseServings_Positive", "[BaseServings] > 0");

                            t.HasCheckConstraint("CK_Recipes_Status", "[Status] IN (N'Draft', N'Published')");
                        });
                });

            modelBuilder.Entity("SmartKitchenAssistant.Api.Features.Recipes.Domain.RecipeIngredient", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("DisplayUnit")
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<long>("IngredientId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsOptional")
                        .HasColumnType("bit");

                    b.Property<decimal?>("NormalizedQuantity")
                        .HasPrecision(18, 6)
                        .HasColumnType("decimal(18,6)");

                    b.Property<long>("RecipeId")
                        .HasColumnType("bigint");

                    b.Property<int>("Sequence")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IngredientId");

                    b.HasIndex("RecipeId", "Sequence")
                        .IsUnique();

                    b.ToTable("RecipeIngredients", "recipes", t =>
                        {
                            t.HasCheckConstraint("CK_RecipeIngredients_DisplayUnit", "[DisplayUnit] IS NULL OR [DisplayUnit] IN (N'Gram', N'Kilogram', N'Milliliter', N'Liter', N'Each')");

                            t.HasCheckConstraint("CK_RecipeIngredients_NormalizedQuantity_Positive", "[NormalizedQuantity] IS NULL OR [NormalizedQuantity] > 0");

                            t.HasCheckConstraint("CK_RecipeIngredients_QuantityAndUnit_Paired", "([NormalizedQuantity] IS NULL AND [DisplayUnit] IS NULL) OR ([NormalizedQuantity] IS NOT NULL AND [DisplayUnit] IS NOT NULL)");

                            t.HasCheckConstraint("CK_RecipeIngredients_Sequence_Positive", "[Sequence] > 0");
                        });
                });

            modelBuilder.Entity("SmartKitchenAssistant.Api.Features.Recipes.Domain.RecipeStep", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Instruction")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<long>("RecipeId")
                        .HasColumnType("bigint");

                    b.Property<int>("Sequence")
                        .HasColumnType("int");

                    b.Property<int?>("TimerSeconds")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RecipeId", "Sequence")
                        .IsUnique();

                    b.ToTable("RecipeSteps", "recipes", t =>
                        {
                            t.HasCheckConstraint("CK_RecipeSteps_Sequence_Positive", "[Sequence] > 0");

                            t.HasCheckConstraint("CK_RecipeSteps_TimerSeconds_Positive", "[TimerSeconds] IS NULL OR [TimerSeconds] > 0");
                        });
                });

            modelBuilder.Entity("SmartKitchenAssistant.Api.Features.Pantry.Domain.UserPantryItem", b =>
                {
                    b.HasOne("SmartKitchenAssistant.Api.Features.Catalog.Domain.Ingredient", null)
                        .WithMany()
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("SmartKitchenAssistant.Api.Features.Recipes.Domain.RecipeIngredient", b =>
                {
                    b.HasOne("SmartKitchenAssistant.Api.Features.Catalog.Domain.Ingredient", null)
                        .WithMany()
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("SmartKitchenAssistant.Api.Features.Recipes.Domain.Recipe", null)
                        .WithMany()
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SmartKitchenAssistant.Api.Features.Recipes.Domain.RecipeStep", b =>
                {
                    b.HasOne("SmartKitchenAssistant.Api.Features.Recipes.Domain.Recipe", null)
                        .WithMany()
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
